"""
Automated LaTeX Table Generation Script

Generates LaTeX tables from persona vector analysis results.
Replaces hardcoded tables with auto-generated content from actual experimental results.

Usage:
    python generate_latex_tables.py --persona_vectors_dir persona_vectors --output_dir paper/tables
    python generate_latex_tables.py --persona_vectors_dir persona_vectors --output_dir paper/tables --version v1
"""

import argparse
import os
import json
from pathlib import Path
from typing import Dict, List, Any, Optional


def load_analysis_results(
    persona_vectors_dir: str, model_name: str, trait_name: str, version: str = "v2"
) -> Optional[Dict]:
    """Load analysis results for a model-trait combination."""
    model_short = model_name.replace("/", "_")

    # Try v2 naming first, then v1
    if version == "v2":
        analysis_file = os.path.join(
            persona_vectors_dir,
            model_short,
            trait_name,
            f"analysis_v2_{trait_name}.json",
        )
        if not os.path.exists(analysis_file):
            analysis_file = os.path.join(
                persona_vectors_dir,
                model_short,
                trait_name,
                f"analysis_{trait_name}.json",
            )
    else:
        analysis_file = os.path.join(
            persona_vectors_dir, model_short, trait_name, f"analysis_{trait_name}.json"
        )

    if os.path.exists(analysis_file):
        with open(analysis_file, "r") as f:
            return json.load(f)
    return None


def get_best_metrics(analysis: Dict) -> Dict[str, Any]:
    """Extract best metrics from analysis results."""
    layers = analysis.get("layers", {})

    if not layers:
        return {
            "best_layer": 0,
            "best_loso_acc": 0.0,
            "cohens_d": 0.0,
            "snr": 0.0,
        }

    # Find best layer by LOSO accuracy
    best_layer = None
    best_loso_acc = 0.0
    best_cohens_d = 0.0
    best_snr = 0.0

    for layer_idx, layer_data in layers.items():
        # Handle both string and int keys
        layer_idx = int(layer_idx) if isinstance(layer_idx, str) else layer_idx

        loso_acc = layer_data.get("loso_accuracy", 0.0)
        if loso_acc > best_loso_acc:
            best_loso_acc = loso_acc
            best_layer = layer_idx
            best_cohens_d = layer_data.get("cohens_d", 0.0)
            best_snr = layer_data.get("signal_to_noise_ratio", 0.0)

    return {
        "best_layer": best_layer if best_layer is not None else 0,
        "best_loso_acc": best_loso_acc,
        "cohens_d": best_cohens_d,
        "snr": best_snr,
    }


def generate_cross_model_table(
    persona_vectors_dir: str, models: List[str], traits: List[str], version: str = "v2"
) -> str:
    """Generate LaTeX table for cross-model extraction summary."""

    # Table header
    latex = [
        "% AUTO-GENERATED TABLE - Cross-model extraction summary",
        "% Generated by generate_latex_tables.py",
        "% Do not edit manually - will be overwritten on regeneration",
        "",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{\\textbf{Cross-model extraction summary (Big Five).} LOSO accuracy, Cohen's $d$, and SNR at each model's optimal layer. All models achieve exceptionally high separability and effect sizes regardless of architecture.}",
        "\\label{tab:cross_model_summary}",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "\\textbf{Model} & \\textbf{Best LOSO Layer} & \\textbf{Mean LOSO Acc.} & \\textbf{Cohen's $d$} & \\textbf{SNR} \\\\",
        "\\midrule",
    ]

    # Load data for each model
    for model_name in models:
        model_short = model_name.replace("/", "_")
        model_display = model_name.split("/")[-1]  # Get last part of model name

        # Aggregate metrics across all traits
        all_loso_accs = []
        all_cohens_ds = []
        all_snrs = []
        best_layers = []

        for trait_name in traits:
            analysis = load_analysis_results(
                persona_vectors_dir, model_name, trait_name, version
            )
            if analysis:
                metrics = get_best_metrics(analysis)
                all_loso_accs.append(metrics["best_loso_acc"])
                all_cohens_ds.append(metrics["cohens_d"])
                all_snrs.append(metrics["snr"])
                best_layers.append(metrics["best_layer"])

        if all_loso_accs:
            # Calculate mean metrics
            mean_loso_acc = sum(all_loso_accs) / len(all_loso_accs)
            mean_cohens_d = sum(all_cohens_ds) / len(all_cohens_ds)
            mean_snr = sum(all_snrs) / len(all_snrs)
            mean_best_layer = int(sum(best_layers) / len(best_layers))

            # Format row
            row = f"{model_display} & {mean_best_layer} & {mean_loso_acc:.3f} & {mean_cohens_d:.2f} & {mean_snr:.1f} \\\\"
            latex.append(row)

    # Table footer
    latex.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )

    return "\n".join(latex)


def generate_trait_comparison_table(
    persona_vectors_dir: str, model_name: str, traits: List[str], version: str = "v2"
) -> str:
    """Generate LaTeX table comparing different traits for a single model."""

    model_short = model_name.replace("/", "_")
    model_display = model_name.split("/")[-1]

    latex = [
        f"% AUTO-GENERATED TABLE - Trait comparison for {model_display}",
        "% Generated by generate_latex_tables.py",
        "% Do not edit manually - will be overwritten on regeneration",
        "",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{\\textbf{{Persona vector extraction results for {model_display}.}} Comparison of Big Five traits and defense mechanisms.}}",
        f"\\label{{tab:trait_comparison_{model_short}}}",
        "\\begin{tabular}{lcccc}",
        "\\toprule",
        "\\textbf{Trait} & \\textbf{Best Layer} & \\textbf{LOSO Acc.} & \\textbf{Cohen's $d$} & \\textbf{SNR} \\\\",
        "\\midrule",
    ]

    for trait_name in traits:
        analysis = load_analysis_results(
            persona_vectors_dir, model_name, trait_name, version
        )
        if analysis:
            metrics = get_best_metrics(analysis)
            trait_display = trait_name.replace("_", " ").title()

            row = f"{trait_display} & {metrics['best_layer']} & {metrics['best_loso_acc']:.3f} & {metrics['cohens_d']:.2f} & {metrics['snr']:.1f} \\\\"
            latex.append(row)

    latex.extend(
        [
            "\\bottomrule",
            "\\end{tabular}",
            "\\end{table}",
        ]
    )

    return "\n".join(latex)


def generate_all_tables(persona_vectors_dir: str, output_dir: str, version: str = "v2"):
    """Generate all LaTeX tables from experimental results."""

    os.makedirs(output_dir, exist_ok=True)

    # Auto-detect models
    models = []
    if os.path.isdir(persona_vectors_dir):
        for d in os.listdir(persona_vectors_dir):
            model_dir = os.path.join(persona_vectors_dir, d)
            if os.path.isdir(model_dir) and not d.startswith("."):
                # Convert back to model name format
                model_name = d.replace("_", "/", 1)
                models.append(model_name)

    if not models:
        print(f"Warning: No models found in {persona_vectors_dir}")
        return

    print(f"Detected models: {models}")

    # Define traits
    big5_traits = [
        "openness",
        "conscientiousness",
        "extraversion",
        "agreeableness",
        "neuroticism",
    ]
    defense_traits = [
        "humor",
        "projection",
        "rationalization",
        "denial",
        "displacement",
        "intellectualization",
        "regression",
        "reaction_formation",
        "sublimation",
    ]
    all_traits = big5_traits + defense_traits

    # Generate cross-model summary table
    print("Generating cross-model summary table...")
    cross_model_table = generate_cross_model_table(
        persona_vectors_dir, models, big5_traits, version
    )

    output_file = os.path.join(output_dir, "cross_model_summary.tex")
    with open(output_file, "w") as f:
        f.write(cross_model_table)
    print(f"  Saved: {output_file}")

    # Generate per-model trait comparison tables
    for model_name in models:
        print(f"Generating trait comparison table for {model_name}...")
        trait_table = generate_trait_comparison_table(
            persona_vectors_dir, model_name, all_traits, version
        )

        model_short = model_name.replace("/", "_")
        output_file = os.path.join(output_dir, f"trait_comparison_{model_short}.tex")
        with open(output_file, "w") as f:
            f.write(trait_table)
        print(f"  Saved: {output_file}")

    # Generate a master file that includes all tables
    master_latex = [
        "% AUTO-GENERATED MASTER FILE - Include all tables",
        "% Generated by generate_latex_tables.py",
        "% Do not edit manually",
        "",
        "% Cross-model summary table",
        "\\input{tables/cross_model_summary}",
        "",
    ]

    for model_name in models:
        model_short = model_name.replace("/", "_")
        master_latex.append(f"% Trait comparison for {model_name}")
        master_latex.append(f"\\input{{tables/trait_comparison_{model_short}}}")
        master_latex.append("")

    master_file = os.path.join(output_dir, "all_tables.tex")
    with open(master_file, "w") as f:
        f.write("\n".join(master_latex))
    print(f"  Saved master file: {master_file}")

    print(f"\n✓ All tables generated successfully in {output_dir}/")
    print(f"  Include in your LaTeX document with: \\input{{tables/all_tables}}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate LaTeX tables from persona vector analysis results"
    )
    parser.add_argument(
        "--persona_vectors_dir",
        type=str,
        default="persona_vectors",
        help="Directory containing persona vectors (default: persona_vectors)",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="paper/tables",
        help="Output directory for LaTeX table files (default: paper/tables)",
    )
    parser.add_argument(
        "--version",
        type=str,
        default="v2",
        choices=["v1", "v2"],
        help="Version of analysis files to use (default: v2)",
    )
    parser.add_argument(
        "--models",
        type=str,
        default=None,
        help="Comma-separated list of models (auto-detected if not specified)",
    )

    args = parser.parse_args()

    # Validate input directory
    if not os.path.isdir(args.persona_vectors_dir):
        print(f"Error: Directory not found: {args.persona_vectors_dir}")
        print("Please run the pipeline first to generate persona vectors.")
        return 1

    # Generate tables
    generate_all_tables(args.persona_vectors_dir, args.output_dir, args.version)

    return 0


if __name__ == "__main__":
    exit(main())
